---
title: "For Iris"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{For Iris}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 8,
  fig.height = 8,
  out.width = "100%"
)
```

```{r setup}
library(webmorphR)
library(geomorph)
```


## Load a directory of templates
```{r}
path <- system.file("extdata/composite/", package = "webmorphR")
stimlist <- read_stim(path, "tem$")
```

## Save as TPS and read from TPS

```{r}
path_to_tps <- tempfile(fileext = ".tps")
write_tps(stimlist, path_to_tps)
gm_data <- readland.tps(path_to_tps, specID = "ID")

plotAllSpecimens(gm_data)
```

## Or, just get from stimlist

```{r}
wm_data <- tems_to_array(stimlist)

plotAllSpecimens(wm_data)
```



## Buggy Bezier Curves

```{r avg-plot, fig.height = 4}
faces("test") %>%
  plot(pt.plot = TRUE,
       line.plot = "bezier",
       line.colour = "blue",
       line.alpha = 0.25
  )
```
